name: 'Auto Grader'
description: 'Grade an assignment and release their score'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-token }}
