# action.yml
name: 'Auto Grader'
description: 'Grade an assignment and release their score'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  repo-name:
    description: 'The repository name'
outputs:
  build_output:
    description: 'Build Output'
  test_output:
    description: 'Test Output'
  score:
    description: 'Points Scored'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-token }}
    - ${{ inputs.repo-name }}
