# action.yml
name: 'Auto Grader'
description: 'Grade an assignment and release their score'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  build_output:
    description: 'Build Output'
  test_output:
    description: 'Test Output'
  score:
    description: 'Points Scored'
